version: "3.9"

services:
  fhir-server:
#    image: costateixeira/hapi-fhir-jpaserver-starter:latest
    image: hapiproject/hapi:latest
    restart: on-failure
    container_name: hapiR5
    ports:
      - ${server_port:-8080}:8080
    environment:
      #      - spring.config.location=${ig_url}/application.yaml
      - spring.config.location=file:///application.yaml
      - hapi.fhir.fhir_version=${fhir_version}
      - hapi.fhir.staticlocation=file:/apps
#      - hapi.fhir.implementationguides.${ig_name:-ig}.url=${ig_url}/package.tgz
#      - hapi.fhir.implementationguides.${ig_name:-ig}.name=${ig_package_name}
#      - hapi.fhir.implementationguides.${ig_name:-ig}.version=${ig_version}
    volumes:
      - ./apps:/apps
      - ./application.yaml:/application.yaml
    depends_on:
      - hapi-postgres

  hapi-postgres:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    container_name: hapi-postgres
    restart: always
    environment:
      - POSTGRES_DB=hapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - hapi-postgres:/var/lib

volumes:
  hapi-postgres:
    driver: local