version: "3.9"

services:
  fhir-server:
#    image: hapiproject/hapi:latest
    image: costateixeira/hapi-fhir-jpaserver-starter:latest
    restart: on-failure
    container_name: hapiR5
#    platform: linux/amd64
    ports:
      - ${server_port:-8080}:8080
    volumes:
      - ./apps:/apps
      - ./application-dev.yaml:/application.yaml
    environment:
      #      - spring.config.location=${ig_url}/application.yaml
      - spring.config.location=file:///application.yaml
      - hapi.fhir.fhir_version=${fhir_version}
      - hapi.fhir.staticContentBase=apps
#      - hapi.fhir.implementationguides.${ig_name:-ig}.url=${ig_url}/package.tgz
#      - hapi.fhir.implementationguides.${ig_name:-ig}.name=${ig_package_name}
#      - hapi.fhir.implementationguides.${ig_name:-ig}.version=${ig_version}
#    depends_on:
#      - hapi-postgres

#  hapi-postgres:
#    image: postgres:14.1-alpine
#    ports:
#      - '5432:5432'
#    container_name: hapi-postgres
#    restart: always
#    environment:
#      - POSTGRES_DB=hapi
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - hapi-postgres:/var/lib/postgresql/data

#  ember:
#    image: jkiddo/ember:latest
#    environment:
#      - location=${ig_url}/package.tgz
#      - serverBase=http://fhir-server:8080/fhir  # Leave this as is, this is ember stuff

#volumes:
#  hapi-postgres:
#    driver: local
