version: "3.9"

services:
  fhir-server:
#    image: costateixeira/hapi-fhir-jpaserver-starter:latest
    image: hapiproject/hapi:latest
    restart: on-failure
    container_name: hapiR5
#    platform: linux/amd64
    ports:
      - ${server_port:-8080}:8080
    environment:
      #      - spring.config.location=${ig_url}/application.yaml
      - spring.config.location=file:///application.yaml
      - hapi.fhir.fhir_version=${fhir_version}
      - hapi.fhir.staticContentBase=apps
#      - hapi.fhir.implementationguides.${ig_name:-ig}.url=${ig_url}/package.tgz
#      - hapi.fhir.implementationguides.${ig_name:-ig}.name=${ig_package_name}
#      - hapi.fhir.implementationguides.${ig_name:-ig}.version=${ig_version}
    volumes:
      - ./apps:/apps
      - ./application.yaml:/application.yaml
